set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(MINGW_SDL2_ROOT "/opt/ai-agent/mingw64" CACHE PATH "MinGW SDL2 prefix")
set(CMAKE_PREFIX_PATH "${MINGW_SDL2_ROOT}")
set(CMAKE_FIND_ROOT_PATH "${MINGW_SDL2_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

include_directories(SYSTEM "${MINGW_SDL2_ROOT}/include")
link_directories("${MINGW_SDL2_ROOT}/lib")

set(ENV{PKG_CONFIG_PATH} "${MINGW_SDL2_ROOT}/lib/pkgconfig")
set(ENV{PKG_CONFIG_LIBDIR} "${MINGW_SDL2_ROOT}/lib/pkgconfig")
